create schema staging;
create schema datamart;

DROP TABLE IF EXISTS STAGING.STG_1CP;
CREATE TABLE STAGING.STG_1CP (
	REGIS_CNTRY_CODE								VARCHAR(3) NOT NULL,
	REGIS_CTY_CODE 									SMALLINT NOT NULL,
	REGIS_ID 										BIGINT NOT NULL,
	REGIS_LTY_ID 									VARCHAR(40),
	REGIS_CNSM_ID 									VARCHAR(40) NOT NULL,
	REGIS_DATE 										VARCHAR(20) NOT NULL,
	REGIS_TIME 										VARCHAR(100) NOT NULL,
	REGIS_CHANNEL 									VARCHAR(20),
	REGIS_GENDER 									CHAR,
	REGIS_CITY 										VARCHAR(100),
	CHILD_ID 										FLOAT,
	CHILD_NB 										SMALLINT,
	CHILD_GENDER 									CHAR,
	CHILD_DOB 										VARCHAR(20),
	CHILD_DECEASED									VARCHAR,
	INS_TS										    TIMESTAMP NOT NULL
)
DISTSTYLE KEY DISTKEY (REGIS_ID)
SORTKEY (INS_TS);


DROP TABLE IF EXISTS DATAMART.REGIS_DIM;
CREATE TABLE DATAMART.REGIS_DIM (
    CTY_CODE                                        SMALLINT,
	REGIS_ID										BIGINT NOT NULL,
	LTY_ID 											VARCHAR(40),
	CNSM_ID											VARCHAR(40) NOT NULL,
	REGIS_DATE										DATE NOT NULL,
	REGIS_TIME									    TIMESTAMP NOT NULL,
	REGIS_CHANNEL									VARCHAR(20),
	REGIS_GENDER 									CHAR,
	REGIS_CITY										VARCHAR(100),
	INS_TS	    									DATE NOT NULL
)
DISTSTYLE KEY DISTKEY(LTY_ID);

